"use client";
import {FormEvent, useEffect, useState} from "react";
import {api, Endpoint} from "../lib/api";
export default function Home() {
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[endpoints,setEndpoints]=useState<Endpoint[]>([]),[name,setName]=useState(""),[error,setError]=useState(""),[authenticated,setAuthenticated]=useState(false);
 const load=()=>api<Endpoint[]>("/api/v1/endpoints").then(setEndpoints).catch(()=>{}); useEffect(()=>{if(localStorage.getItem("rbx_token")){setAuthenticated(true);load()}},[]);
 async function login(e:FormEvent, register=false){e.preventDefault();try {const d=await api<{access_token:string}>(`/api/v1/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("rbx_token",d.access_token);setAuthenticated(true);load();}catch(e){setError(e instanceof Error?e.message:"Unable to authenticate")}}
 async function create(e:FormEvent){e.preventDefault();try {await api("/api/v1/endpoints",{method:"POST",body:JSON.stringify({name})});setName("");load()}catch(e){setError(e instanceof Error?e.message:"Unable to create endpoint")}}
 if(!authenticated) return <main className="min-h-screen grid place-items-center p-6"><form className="w-full max-w-md rounded-xl border border-zinc-800 bg-zinc-950 p-8 space-y-4" onSubmit={login}><p className="text-2xl font-bold text-white">RequestBin<span className="text-cyan-400">X</span></p><p className="text-zinc-400">Capture, inspect, replay.</p><input className="w-full rounded bg-zinc-900 p-3" placeholder="email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="w-full rounded bg-zinc-900 p-3" placeholder="password (12+ chars)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="text-red-400">{error}</p>}<button className="w-full rounded bg-cyan-500 p-3 text-zinc-950 font-bold">Sign in</button><button type="button" onClick={e=>login(e,true)} className="w-full text-sm text-cyan-300">Create account</button></form></main>;
 return <main className="mx-auto max-w-5xl p-8"><header className="flex justify-between items-center mb-12"><h1 className="text-2xl font-bold">RequestBin<span className="text-cyan-400">X</span></h1><button onClick={()=>{localStorage.removeItem("rbx_token");location.reload()}} className="text-zinc-400">Sign out</button></header><form onSubmit={create} className="flex gap-3 mb-8"><input className="flex-1 rounded bg-zinc-900 p-3" placeholder="Endpoint name" value={name} onChange={e=>setName(e.target.value)}/><button className="rounded bg-cyan-500 px-5 text-zinc-950 font-bold">New endpoint</button></form><section className="grid gap-3">{endpoints.map(e=><a className="block rounded-lg border border-zinc-800 p-5 hover:border-cyan-500" href={`/endpoints/${e.id}`} key={e.id}><strong>{e.name}</strong><p className="mt-2 text-sm text-zinc-400">/h/{e.token}</p></a>)}{!endpoints.length&&<p className="text-zinc-500">No endpoints yet. Create one to start inspecting traffic.</p>}</section></main>
}
