"use client";
import {use, useEffect, useMemo, useState} from "react";
import {api, API, Captured, Endpoint} from "../../../lib/api";
type Detail = Captured & {headers:Record<string,string>;query:Record<string,string>;cookies:Record<string,string>;body:string|null;protocol:string;user_agent:string|null};
export default function EndpointInspector({params}:{params:Promise<{id:string}>}) {
 const {id}=use(params); const [endpoint,setEndpoint]=useState<Endpoint>(); const [items,setItems]=useState<Captured[]>([]); const [selected,setSelected]=useState<Detail>(); const [tab,setTab]=useState("Overview");
 useEffect(()=>{api<Endpoint[]>("/api/v1/endpoints").then(xs=>setEndpoint(xs.find(x=>x.id===id))); api<Captured[]>(`/api/v1/endpoints/${id}/requests`).then(setItems)},[id]);
 useEffect(()=>{if(!endpoint)return; const ws=new WebSocket(`${API.replace(/^http/,"ws")}/ws/h/${endpoint.token}`); ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==="captured") api<Captured[]>(`/api/v1/endpoints/${id}/requests`).then(setItems)}; const ping=setInterval(()=>ws.readyState===1&&ws.send("ping"),25000);return()=>{clearInterval(ping);ws.close()}},[endpoint,id]);
 function choose(r:Captured){api<Detail>(`/api/v1/requests/${r.id}`).then(setSelected)}
 async function copy(){if(endpoint)await navigator.clipboard.writeText(`${location.origin.replace(":3000",":8000")}/h/${endpoint.token}`)}
 async function replay(){if(!selected)return;const target=prompt("Replay target URL (public internet only)");if(!target)return; try {const result=await api<{status_code:number;latency_ms:number;error?:string}>(`/api/v1/requests/${selected.id}/replay`,{method:"POST",body:JSON.stringify({target_url:target,method:selected.method,headers:selected.headers,body:selected.body})});alert(result.error??`Response ${result.status_code} in ${result.latency_ms}ms`)}catch(e){alert(e instanceof Error?e.message:"Replay failed")}}
 const body=useMemo(()=>{try{return selected?.body?JSON.stringify(JSON.parse(selected.body),null,2):"(empty)"}catch{return selected?.body??"(empty)"}},[selected]);
 return <main className="h-screen grid grid-rows-[auto_1fr]"><header className="border-b border-zinc-800 px-6 py-4 flex gap-4 items-center"><a href="/" className="text-zinc-400">← Endpoints</a><strong>{endpoint?.name??"Loading…"}</strong><code className="ml-auto text-cyan-300">/h/{endpoint?.token}</code><button onClick={copy} className="rounded border border-zinc-700 px-3 py-1">Copy URL</button></header><div className="grid grid-cols-[340px_1fr] overflow-hidden"><aside className="border-r border-zinc-800 overflow-auto"><div className="p-4 text-xs uppercase tracking-wider text-zinc-500">Live requests · {items.length}</div>{items.map(r=><button onClick={()=>choose(r)} key={r.id} className={`block w-full text-left px-4 py-3 border-b border-zinc-900 hover:bg-zinc-900 ${selected?.id===r.id?"bg-zinc-900":""}`}><span className="text-cyan-400 mr-2">{r.method}</span><span>{r.path}</span><p className="mt-1 text-xs text-zinc-500">{new Date(r.received_at).toLocaleTimeString()} · {r.body_size} B</p></button>)}</aside><section className="overflow-auto p-7">{!selected?<div className="grid place-items-center h-full text-zinc-500">Incoming requests appear here in real time.</div>:<><div className="flex items-center gap-3 mb-6"><span className="rounded bg-cyan-400 px-2 py-1 text-sm font-bold text-zinc-950">{selected.method}</span><h2 className="text-xl">{selected.path}</h2><button onClick={replay} className="ml-auto rounded bg-cyan-500 px-4 py-2 font-bold text-zinc-950">Replay</button></div><nav className="flex border-b border-zinc-800 mb-5 gap-5">{["Overview","Headers","Query","Cookies","Body","Raw"].map(x=><button key={x} onClick={()=>setTab(x)} className={`pb-3 ${tab===x?"border-b-2 border-cyan-400 text-cyan-300":"text-zinc-500"}`}>{x}</button>)}</nav>{tab==="Overview"&&<dl className="grid grid-cols-2 gap-5 text-sm"><div><dt className="text-zinc-500">Source IP</dt><dd>{selected.source_ip}</dd></div><div><dt className="text-zinc-500">Content type</dt><dd>{selected.content_type??"—"}</dd></div><div><dt className="text-zinc-500">Protocol</dt><dd>HTTP/{selected.protocol}</dd></div><div><dt className="text-zinc-500">Size</dt><dd>{selected.body_size} bytes</dd></div></dl>}{tab==="Body"&&<pre className="whitespace-pre-wrap overflow-auto rounded-lg bg-zinc-950 p-5 text-sm text-emerald-300">{body}</pre>}{["Headers","Query","Cookies"].includes(tab)&&<pre className="whitespace-pre-wrap rounded-lg bg-zinc-950 p-5 text-sm">{JSON.stringify(tab==="Headers"?selected.headers:tab==="Query"?selected.query:selected.cookies,null,2)}</pre>}{tab==="Raw"&&<pre className="whitespace-pre-wrap rounded-lg bg-zinc-950 p-5 text-sm">{selected.method} {selected.path}{"\n"}{Object.entries(selected.headers).map(([k,v])=>`${k}: ${v}`).join("\n")}{"\n\n"}{selected.body}</pre>}</>}</section></div></main>
}
